# Data Preprocessing

In [1]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
# load the dataset 

df = pd.read_csv("C:\\Users\\Shree\\Documents\\MACHINE_LEARNING\\Fraud_detection_project\\data\\raw\\PS_20174392719_1491204439457_log.csv")

In [4]:
# top rows from the dataset

df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [5]:
# last rows from the dataset

df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.0,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.0,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.0,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.0,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.0,C873221189,6510099.11,7360101.63,1,0

In [6]:
# information about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [7]:
# statistical summary of the dataset

df.describe()

,step,amount,oldbalanceOrg,newbalanceOrig,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
count,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06,6.362620e+06
mean,2.433972e+02,1.798619e+05,8.338831e+05,8.551137e+05,1.100702e+06,1.224996e+06,1.290820e-03,2.514687e-06
std,1.423320e+02,6.038582e+05,2.888243e+06,2.924049e+06,3.399180e+06,3.674129e+06,3.590480e-02,1.585775e-03
min,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.560000e+02,1.338957e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.390000e+02,7.487194e+04,1.420800e+04,0.000000e+00,1.327057e+05,2.146614e+05,0.000000e+00,0.000000e+00
75%,3.350000e+02,2.087215e+05,1.073152e+05,1.442584e+05,9.430367e+05,1.111909e+06,0.000000e+00,0.000000e+00
max,7.430000e+02,9.244552e+07,5.958504e+07,4.958504e+07,3.560159e+08,3.561793e+08,1.000000e+00,1.000000e+00

In [8]:
# check the shape of the dataset

df.shape

(6362620, 11)

In [9]:
# check the missing values

df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [10]:
print(df["isFraud"].value_counts())
print(df["isFraud"].value_counts(normalize=True)*100)

isFraud
0    6354407
1       8213
Name: count, dtype: int64
isFraud
0    99.870918
1     0.129082
Name: proportion, dtype: float64

In [11]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df.drop("isFraud", axis=1)
y = df["isFraud"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y
)

print("Original training distribution:")
print(y_train.value_counts())

print("\nOriginal test distribution:")
print(y_test.value_counts())

Original training distribution:
isFraud
0    5083526
1       6570
Name: count, dtype: int64

Original test distribution:
isFraud
0    1270881
1       1643
Name: count, dtype: int64

In [16]:
# Combine training X and y temporarily
train_df = X_train.copy()
train_df["isFraud"] = y_train.values

# Separate classes
fraud = train_df[train_df["isFraud"] == 1]
normal = train_df[train_df["isFraud"] == 0]

print("Fraud:", len(fraud))
print("Normal:", len(normal))

Fraud: 6570
Normal: 5083526

In [21]:
from sklearn.model_selection import train_test_split

# Split dataset into train and test
train, test = train_test_split(df, test_size=0.2, random_state=42)

balanced_train = train.copy()

In [22]:
# Separate the classes
fraud = balanced_train[balanced_train["isFraud"] == 1]
normal = balanced_train[balanced_train["isFraud"] == 0]

# Take first len(fraud) normal records
normal_sample = normal.iloc[:len(fraud)]

# Combine both classes
balanced_50_50 = pd.concat([normal_sample, fraud], axis=0)

# Reset index
balanced_50_50 = balanced_50_50.reset_index(drop=True)

# Check distribution
print(balanced_50_50["isFraud"].value_counts())

isFraud
0    6593
1    6593
Name: count, dtype: int64

In [23]:
print("Original training rows:", len(X_train))
print("Balanced training rows:", len(balanced_50_50))

Original training rows: 5090096
Balanced training rows: 13186

In [24]:
important_columns = [
    "amount",
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest"
]

print("Original Training:")
print(X_train[important_columns].describe())

print("\nBalanced Training:")
print(balanced_50_50[important_columns].describe())

Original Training:
             amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
count  5.090096e+06   5.090096e+06    5.090096e+06    5.090096e+06
mean   1.800458e+05   8.339300e+05    8.552094e+05    1.100910e+06
std    6.056318e+05   2.889692e+06    2.925598e+06    3.393492e+06
min    0.000000e+00   0.000000e+00    0.000000e+00    0.000000e+00
25%    1.338083e+04   0.000000e+00    0.000000e+00    0.000000e+00
50%    7.487786e+04   1.418700e+04    0.000000e+00    1.326287e+05
75%    2.088449e+05   1.072990e+05    1.443188e+05    9.437157e+05
max    9.244552e+07   5.958504e+07    4.958504e+07    3.560159e+08

       newbalanceDest
count    5.090096e+06
mean     1.225413e+06
std      3.671119e+06
min      0.000000e+00
25%      0.000000e+00
50%      2.144827e+05
75%      1.112399e+06
max      3.561793e+08

Balanced Training:
             amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
count  1.318600e+04   1.318600e+04    1.318600e+04    1.318600e+04
mean   8.300383e+05   1.262541e+06    5.335378e+05    8.067520e+05
std    1.884126e+06   3.291182e+06    2.529122e+06    3.292182e+06
min    0.000000e+00   0.000000e+00    0.000000e+00    0.000000e+00
25%    3.707424e+04   1.014851e+04    0.000000e+00    0.000000e+00
50%    1.740179e+05   1.175192e+05    0.000000e+00    0.000000e+00
75%    5.410648e+05   8.042426e+05    0.000000e+00    5.185215e+05
max    3.126451e+07   5.958504e+07    4.958504e+07    2.362305e+08

       newbalanceDest
count    1.318600e+04
mean     1.234763e+06
std      3.698922e+06
min      0.000000e+00
25%      0.000000e+00
50%      1.244651e+05
75%      1.087962e+06
max      2.367265e+08

In [25]:
print(X_train["type"].value_counts(normalize=True))

type
CASH_OUT    0.351562
PAYMENT     0.338224
CASH_IN     0.219971
TRANSFER    0.083724
DEBIT       0.006519
Name: proportion, dtype: float64

In [26]:
print(balanced_50_50["type"].value_counts(normalize=True))

type
CASH_OUT    0.428561
TRANSFER    0.288867
PAYMENT     0.170332
CASH_IN     0.108828
DEBIT       0.003413
Name: proportion, dtype: float64

In [27]:
print("Original fraud:", (y_train == 1).sum())
print("Balanced fraud:", (balanced_50_50["isFraud"] == 1).sum())

Original fraud: 6570
Balanced fraud: 6593

In [28]:
print(y_test.value_counts())
print(y_test.value_counts(normalize=True) * 100)

isFraud
0    1270881
1       1643
Name: count, dtype: int64
isFraud
0    99.870887
1     0.129113
Name: proportion, dtype: float64